#!/usr/bin/env bash
# memory-sync-codex.sh
# Claude Code SessionStart + Stop hook: mirror global instructions and memory
# into ~/.codex/AGENTS.md, which Codex CLI reads automatically at startup.
#
# RULE: this file must stay ASCII-only. Non-ASCII bodies pass through as data.

set -u

claude_dir="${CLAUDE_HOME:-$HOME/.claude}"
projects_dir="$claude_dir/projects"
rules_file="$claude_dir/CLAUDE.md"
codex_dir="${CODEX_HOME:-$HOME/.codex}"
agents_out="$codex_dir/AGENTS.md"
char_limit=6000
total_chars=0
index_parts=""
bodies=""
global_rules=""

if [[ -f "$rules_file" ]]; then
  global_rules="$(cat "$rules_file" 2>/dev/null || true)"
fi

# Rewrite Claude-vs-Codex marker blocks for the Codex-facing copy:
# - <!-- claude-only --> ... <!-- /claude-only --> is dropped entirely
#   (markers and content), since it is Claude-harness-specific.
# - <!-- codex-only ... --> keeps only its inner content (markers removed),
#   since Claude ignores it as an HTML comment but Codex should see it.
# Unclosed/malformed markers just stop emitting from that point on; the
# script still completes and writes AGENTS.md normally (fail-open).
if [[ -n "$global_rules" ]]; then
  global_rules="$(
    printf '%s\n' "$global_rules" | awk '
      /^<!-- claude-only -->$/ { skip_claude = 1; next }
      /^<!-- \/claude-only -->$/ { skip_claude = 0; next }
      skip_claude { next }
      /^<!-- codex-only$/ { in_codex_only = 1; next }
      in_codex_only && /^-->$/ { in_codex_only = 0; next }
      { print }
    '
  )"
fi

for store in "$projects_dir"/*--claude; do
  memory_dir="$store/memory"
  index_file="$memory_dir/MEMORY.md"
  [[ -f "$index_file" ]] || continue

  index_content="$(cat "$index_file" 2>/dev/null || true)"
  [[ -n "$index_content" ]] || continue
  if [[ -n "$index_parts" ]]; then
    index_parts+=$'\n\n'
  fi
  index_parts+="$index_content"

  while IFS= read -r relative_path; do
    [[ -n "$relative_path" && "$relative_path" != "AGENTS.md" ]] || continue
    full_path="$memory_dir/$relative_path"
    [[ -f "$full_path" ]] || continue

    body="$(
      awk '
        NR == 1 && $0 ~ /^---\r?$/ { front = 1; next }
        front {
          if ($0 ~ /^---\r?$/) { front = 0 }
          next
        }
        { print }
      ' "$full_path"
    )"
    [[ -n "$body" ]] || continue

    file_name="$(basename "$relative_path" .md)"
    snippet="### $file_name"$'\n'"$body"
    if ((total_chars + ${#snippet} > char_limit)); then
      break
    fi
    if [[ -n "$bodies" ]]; then
      bodies+=$'\n\n---\n\n'
    fi
    bodies+="$snippet"
    total_chars=$((total_chars + ${#snippet}))
  done < <(
    printf '%s\n' "$index_content" |
      grep -oE '\[[^]]*\]\([^)]*\.md\)' 2>/dev/null |
      sed -E 's/.*\(([^)]*)\)/\1/'
  )
done

if [[ -z "$global_rules" && -z "$index_parts" ]]; then
  exit 0
fi

[[ -n "$global_rules" ]] || global_rules="(none)"
[[ -n "$index_parts" ]] || index_parts="(none)"
[[ -n "$bodies" ]] || bodies="(none)"
timestamp="$(date '+%Y-%m-%d %H:%M')"

if [[ ! -d "$codex_dir" ]]; then
  mkdir -p "$codex_dir" || exit 0
fi
temp_file="$(mktemp "$codex_dir/.AGENTS.md.XXXXXX")" || exit 0
cat >"$temp_file" <<EOF
# Claude Code Global Instructions and Cross-Agent Memory
# Auto-generated by ~/.claude/hooks/memory-sync-codex.sh at $timestamp.
# Do not edit by hand - changes will be overwritten.

## Global Instructions

$global_rules

---

## Memory Index

$index_parts

---

## Memory Contents

$bodies
EOF
mv "$temp_file" "$agents_out"
exit 0
