# memory-sync-codex.ps1
# Claude Code SessionStart + Stop hook: mirror the Claude Code memory store(s)
# into ~/.codex/AGENTS.md, which Codex CLI reads automatically at startup
# (no config.toml changes needed).
#
# RULE: this file must stay ASCII-only (Japanese literals in hook .ps1 files
# have previously broken parsing). Memory bodies pass through as data only.

$ErrorActionPreference = "SilentlyContinue"
$claudeDir   = if ($env:CLAUDE_HOME) { $env:CLAUDE_HOME } else { "$env:USERPROFILE\.claude" }
$projectsDir = Join-Path $claudeDir "projects"
$rulesFile   = Join-Path $claudeDir "CLAUDE.md"
$codexDir    = if ($env:CODEX_HOME) { $env:CODEX_HOME } else { "$env:USERPROFILE\.codex" }
$agentsOut   = Join-Path $codexDir "AGENTS.md"
$globalRules = Get-Content $rulesFile -Raw -Encoding UTF8 2>$null

# Same portable store resolution as memory-inject.ps1: every synced PC creates
# a slug like C--Users-<username>--claude under projects/.
$memStores = @(Get-ChildItem $projectsDir -Directory -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -match '^[cC]--Users-.+--claude$' -and (Test-Path (Join-Path $_.FullName "memory\MEMORY.md")) })

$charLimit  = 6000
$totalChars = 0
$indexParts = @()
$bodies     = @()

foreach ($store in $memStores) {
    $memDir       = Join-Path $store.FullName "memory"
    $indexContent = Get-Content (Join-Path $memDir "MEMORY.md") -Raw -Encoding UTF8 2>$null
    if (-not $indexContent) { continue }
    $indexParts += $indexContent.Trim()

    $links = [regex]::Matches($indexContent, '\[.*?\]\((.+?\.md)\)')
    foreach ($link in $links) {
        $relPath = $link.Groups[1].Value
        if ($relPath -eq "AGENTS.md") { continue }
        $fullPath = Join-Path $memDir $relPath
        if (-not (Test-Path $fullPath)) { continue }

        $body = Get-Content $fullPath -Raw -Encoding UTF8 2>$null
        if (-not $body) { continue }

        $body     = ($body -replace '(?s)^---.*?---\s*', '').Trim()
        $fileName = [System.IO.Path]::GetFileNameWithoutExtension($relPath)
        $snippet  = "### $fileName`n$body"

        if (($totalChars + $snippet.Length) -gt $charLimit) { break }
        $bodies     += $snippet
        $totalChars += $snippet.Length
    }
}

if (-not $globalRules -and $indexParts.Count -eq 0) { exit 0 }

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"
$rulesSection = if ($globalRules) { $globalRules.Trim() } else { "(none)" }
$indexSection = if ($indexParts.Count -gt 0) { $indexParts -join "`n`n" } else { "(none)" }
$bodySection = if ($bodies.Count -gt 0) { $bodies -join "`n`n---`n`n" } else { "(none)" }

$agentsContent = @"
# Claude Code Global Instructions and Cross-Agent Memory
# Auto-generated by ~/.claude/hooks/memory-sync-codex.ps1 at $timestamp.
# Do not edit by hand - changes will be overwritten.

## Global Instructions

$rulesSection

---

## Memory Index

$indexSection

---

## Memory Contents

$bodySection
"@

if (-not (Test-Path $codexDir)) { New-Item -ItemType Directory -Path $codexDir | Out-Null }
[System.IO.File]::WriteAllText($agentsOut, $agentsContent, (New-Object System.Text.UTF8Encoding($false)))
exit 0
