# memory-sync-codex.ps1
# Claude Code SessionStart + Stop hook: mirror the Claude Code memory store(s)
# into ~/.codex/AGENTS.md, which Codex CLI reads automatically at startup
# (no config.toml changes needed).
#
# RULE: this file must stay ASCII-only (Japanese literals in hook .ps1 files
# have previously broken parsing). Memory bodies pass through as data only.

$ErrorActionPreference = "SilentlyContinue"
$projectsDir = "$env:USERPROFILE\.claude\projects"
$codexDir    = "$env:USERPROFILE\.codex"
$agentsOut   = Join-Path $codexDir "AGENTS.md"

# Same portable store resolution as memory-inject.ps1: every synced PC creates
# a slug like C--Users-<username>--claude under projects/.
$memStores = @(Get-ChildItem $projectsDir -Directory -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -match '^[cC]--Users-.+--claude$' -and (Test-Path (Join-Path $_.FullName "memory\MEMORY.md")) })
if ($memStores.Count -eq 0) { exit 0 }

$charLimit  = 6000
$totalChars = 0
$indexParts = @()
$bodies     = @()

foreach ($store in $memStores) {
    $memDir       = Join-Path $store.FullName "memory"
    $indexContent = Get-Content (Join-Path $memDir "MEMORY.md") -Raw -Encoding UTF8 2>$null
    if (-not $indexContent) { continue }
    $indexParts += $indexContent.Trim()

    $links = [regex]::Matches($indexContent, '\[.*?\]\((.+?\.md)\)')
    foreach ($link in $links) {
        $relPath = $link.Groups[1].Value
        if ($relPath -eq "AGENTS.md") { continue }
        $fullPath = Join-Path $memDir $relPath
        if (-not (Test-Path $fullPath)) { continue }

        $body = Get-Content $fullPath -Raw -Encoding UTF8 2>$null
        if (-not $body) { continue }

        $body     = ($body -replace '(?s)^---.*?---\s*', '').Trim()
        $fileName = [System.IO.Path]::GetFileNameWithoutExtension($relPath)
        $snippet  = "### $fileName`n$body"

        if (($totalChars + $snippet.Length) -gt $charLimit) { break }
        $bodies     += $snippet
        $totalChars += $snippet.Length
    }
}

if ($indexParts.Count -eq 0) { exit 0 }

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"

$agentsContent = @"
# Cross-Agent Memory (Claude Code -> Codex)
# Auto-generated by ~/.claude/hooks/memory-sync-codex.ps1 at $timestamp.
# Do not edit by hand - changes will be overwritten.

This file mirrors the Claude Code memory store(s) under
~/.claude/projects/<slug>--claude/memory/. Use it to keep context consistent
across sessions and agents.

## Memory Index

$($indexParts -join "`n`n")

---

## Memory Contents

$($bodies -join "`n`n---`n`n")
"@

if (-not (Test-Path $codexDir)) { New-Item -ItemType Directory -Path $codexDir | Out-Null }
[System.IO.File]::WriteAllText($agentsOut, $agentsContent, (New-Object System.Text.UTF8Encoding($false)))
exit 0
